DATABASE MDM;

REPLACE VIEW MDM.AGE_MIN_MAX
AS
LOCKING ROW FOR ACCESS
SEL A.MINAGE MIN_AGE,B.MAXAGE MAX_AGE, A.COUNTRY FROM
(SELECT
CHI.AV_DESCRIPTION MINAGE, PAR.AV_DESCRIPTION COUNTRY, CHI.AV_CODE AGECODE
FROM
ATTRIBUTE_VALUES PAR, ATTRIBUTE_VALUES_HIERARCHY HI, ATTRIBUTE_VALUES CHI
WHERE
CHI.AV_CODE IN ('MIN') AND
PAR.AV_ID = HI.AV_ID_PARENT AND
HI.AV_ID_CHILD = CHI.AV_ID
) A,
	(SELECT
CHI.AV_DESCRIPTION MAXAGE, PAR.AV_DESCRIPTION COUNTRY, CHI.AV_CODE AGECODE
FROM
ATTRIBUTE_VALUES PAR, ATTRIBUTE_VALUES_HIERARCHY HI, ATTRIBUTE_VALUES CHI
WHERE
CHI.AV_CODE IN ('MAX') AND
PAR.AV_ID = HI.AV_ID_PARENT AND
HI.AV_ID_CHILD = CHI.AV_ID
) B WHERE A.COUNTRY=B.COUNTRY;

===============================================================================================
REPLACE VIEW MDM_MST.ERR_PRSNA_STG_VIEW
as
LOCKING ROW FOR ACCESS
SEL MKTNG_PGM_NBR,
REGIS_CNSMR_ID_VAL FROM 
MDM_MST.ERR_PRSNA_STG
GROUP BY 1,2
