UPDATE 
ICRM_STAGE_DEV.PRSNA_EMAIL_ADDR_STG
SET
CNTCT_POINT_CATEG_CODE = 'EP';

==============================================

UPDATE 
ICRM_STAGE_DEV.PRSNA_PHONE_STG
SET
CNTCT_POINT_CATEG_CODE = 'PM';
===========================================

UPDATE 
ICRM_STAGE_DEV.PRSNA_POSTL_ADDR_STG
SET
CNTCT_POINT_CATEG_CODE = 'AR'
WHERE
CNTCT_POINT_CATEG_CODE = 'H';

UPDATE 
ICRM_STAGE_DEV.PRSNA_POSTL_ADDR_STG
SET
CNTCT_POINT_CATEG_CODE = 'AB'
WHERE
CNTCT_POINT_CATEG_CODE = 'B';

===============================================

database ICRM_STAGE_DEV

UPDATE CNTCT_OPTN_CHCE_STG
SET
CNTCT_POINT_TYPE_CODE = 'A',
CNTCT_POINT_CATEG_CODE = PRSNA_POSTL_ADDR_STG .CNTCT_POINT_CATEG_CODE
WHERE
CNTCT_OPTN_CHCE_STG.CNTCT_OPTN_NBR = 1.00 
AND
CNTCT_OPTN_CHCE_STG.MKTNG_PGM_NBR = PRSNA_POSTL_ADDR_STG.MKTNG_PGM_NBR 
AND
CNTCT_OPTN_CHCE_STG.REGIS_CNSMR_ID_VAL = PRSNA_POSTL_ADDR_STG.REGIS_CNSMR_ID_VAL 

UPDATE 
ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG
SET
CNTCT_POINT_TYPE_CODE = 'E',
CNTCT_POINT_CATEG_CODE = 'EP'
WHERE
CNTCT_OPTN_NBR = 2.00

 

UPDATE 
ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG
SET
CNTCT_POINT_TYPE_CODE = 'P',
CNTCT_POINT_CATEG_CODE = 'PM'
WHERE
CNTCT_OPTN_NBR = 3.00

==============================================================================

UPDATE ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG
SET CNTCT_OPTN_IND='Y'
WHERE CNTCT_OPTN_NBR=3.00


UPDATE ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG
SET CNTCT_OPTN_IND='N'
WHERE CNTCT_OPTN_NBR !=3.00

==========================================================================

 SELECT * FROM ICRM_STAGE_DEV.PRSNA_EMAIL_ADDR_STG
 SELECT * FROM ICRM_STAGE_DEV.PRSNA_PHONE_STG
 SELECT * FROM ICRM_STAGE_DEV.PRSNA_POSTL_ADDR_STG
 SELECT * FROM  ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG

SELECT DISTINCT CNTCT_POINT_CATEG_CODE FROM  ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG

================================================================================================

SELECT * FROM ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG

SELECT DISTINCT MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,CNTCT_POINT_CATEG_CODE FROM ICRM_STAGE_DEV.PRSNA_POSTL_ADDR_STG

SELECT DISTINCT MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,CNTCT_OPTN_NBR,CNTCT_POINT_TYPE_CODE, CNTCT_POINT_CATEG_CODE  FROM ICRM_STAGE_DEV.CNTCT_OPTN_CHCE_STG
WHERE CNTCT_OPTN_NBR = 1.00 


SELECT * FROM CNTCT_OPTN_CHCE_STG,PRSNA_POSTL_ADDR_STG
WHERE
CNTCT_OPTN_NBR = 1.00 
AND
CNTCT_OPTN_CHCE_STG.MKTNG_PGM_NBR = PRSNA_POSTL_ADDR_STG.MKTNG_PGM_NBR 
AND
CNTCT_OPTN_CHCE_STG.REGIS_CNSMR_ID_VAL = PRSNA_POSTL_ADDR_STG.REGIS_CNSMR_ID_VAL 
========================================================================================================================
ALTER TABLE ICRM_STAGE_DEV.PRSNA_STG
ADD CNTRY_NAME CHAR(3);

UPDATE ICRM_STAGE_DEV.PRSNA_PHONE_STG SET SMS_PREFR_IND='Y';
UPDATE ICRM_STAGE_DEV.PRSNA_PHONE_STG SET PREFR_IND='Y';
UPDATE ICRM_STAGE_DEV.PRSNA_PHONE_STG SET VALID_IND='Y';

INSERT INTO MST_MKTNG_PGM(MKTNG_PGM_NAME,MKTNG_PGM_NBR,LEGAL_ENT_NBR)
VALUES('P&G UK',1,800);


======================================================================

UPDATE	PNGMDM_MST.TRILLIUM_OUTPUT 
SET	REFERENCE_HOUSEHOLD_ID=concat('HH', REFERENCE_HOUSEHOLD_ID); 
UPDATE	PNGMDM_MST.TRILLIUM_OUTPUT 
SET	REFERENCE_REGISTRATIONKEY=concat('RG', REFERENCE_REGISTRATIONKEY);
UPDATE	PNGMDM_MST.TRILLIUM_OUTPUT 
SET	REFERENCE_REGISTRATIONKEY=concat('RG', REFERENCE_LEGALENTITYKEY);

