:: +---------------------------------------------------------------------------+
:: | File:     make_config.cmd                                                 |
:: | Purpose:  Create TS_CONFIG file dynamically for a specific work-area.     |
:: +---------------------------------------------------------------------------+
:: |                                                                           |
:: | Client:   Teradata Corporation                                            |
:: | Project:  1 Consumer Place                                                |
:: | Author:   Sheldon Hartling                                                |
:: | Date:     30-Apr-2012                                                     |
:: |                                                                           |
:: | Usage:                                                                    |
:: |   > make_config                                                           |
:: |                                                                           |
:: | Requires the following environment variables:                             |
:: |   TS_CONFIG   - full path for config file to be created,                  |
:: |   TS_QUALITY  - full path for TSQ13 Software directory,                   |
:: |   TS_POSTAL   - full path for TSQ13 Postal Tables directory,              |
:: |   TS_PROJECT  - full path for project root directory.                     |
:: |   TS_WORKAREA - full path for work-area directory.                        |
:: |                                                                           |
:: |                                                                           |
:: | Return Status:                                                            |
:: |   errorlevel = 0, success                                                 |
:: |   errorlevel = 1, failure                                                 |
:: |                                                                           |
:: |                                                                           |
:: | Change History:                                                           |
:: |                                                                           |
:: |  Date         Author     Description                                      |
:: |  ...........  .........  ...............................................  |
:: |  30-Apr-2012  sheldonh   Created.                                         |      
:: |                                                                           |
:: +---------------------------------------------------------------------------+

   ::                    
   ::... Generate a custom TSQ batch configuration file for specific work area.
   ::

   @echo *>                                                     "%TS_CONFIG%"
   @echo * Custom TSQ batch configuration file>>                "%TS_CONFIG%"
   @echo * generated by %~nx0 on %date% %time%.>>               "%TS_CONFIG%"
   @echo *>>                                                    "%TS_CONFIG%"
   @echo BASEDIR             = "%TS_QUALITY%">>                 "%TS_CONFIG%"
   @echo PROJDIR             = "%TS_PROJECT%">>                 "%TS_CONFIG%"
   @echo WORKAREA            = "%TS_WORKAREA%">>                "%TS_CONFIG%"
   @echo.>>                                                     "%TS_CONFIG%"
   @echo DATABASE            = "$(PROJDIR)">>                   "%TS_CONFIG%"
   @echo INPUT               = "$(WORKAREA)\data">>             "%TS_CONFIG%"
   @echo OUTPUT              = "$(WORKAREA)\data">>             "%TS_CONFIG%"
   @echo DDL                 = "$(PROJDIR)\ddl">>               "%TS_CONFIG%"
   @echo USRTABLES           = "$(PROJDIR)\tables">>            "%TS_CONFIG%"
   @echo WORKSPACE           = "$(WORKAREA)\tmp">>              "%TS_CONFIG%"
   @echo SETTINGS            = "$(PROJDIR)\settings">>          "%TS_CONFIG%"
   @echo LOGS                = "$(WORKAREA)\logs">>             "%TS_CONFIG%"
   @echo STATS               = "$(WORKAREA)\logs">>             "%TS_CONFIG%"
   @echo DEBUG               = "$(WORKAREA)\logs">>             "%TS_CONFIG%"
   @echo DETAILS             = "$(WORKAREA)\logs">>             "%TS_CONFIG%"
   @echo.>>                                                     "%TS_CONFIG%"
   @echo SOFTWARE            = "$(BASEDIR)\..\Software">>       "%TS_CONFIG%"
   @echo TABLES              = "$(BASEDIR)\..\tables">>         "%TS_CONFIG%"
   @echo GENERAL_RESOURCES   = "$(TABLES)\general_resources">>  "%TS_CONFIG%"
   @echo PARSER_RULES        = "$(TABLES)\parser_rules">>       "%TS_CONFIG%"
   @echo CODE_PAGES          = "$(TABLES)\code_pages">>         "%TS_CONFIG%"
   @echo.>>                                                     "%TS_CONFIG%"
   @echo POSTAL_TABLES       = "%TS_POSTAL%\postal_tables">>    "%TS_CONFIG%"
   @echo APAC_POSTAL_TABLES  = "%TS_POSTAL%\aptables">>         "%TS_CONFIG%"
   @echo CENSUS_TABLES       = "%TS_POSTAL%\census_tables">>    "%TS_CONFIG%"
   @echo ACE_TABLES          = "%TS_POSTAL%\ACE_tables">>       "%TS_CONFIG%"
   @echo.>>                                                     "%TS_CONFIG%"
   @echo TSQ_REPORT_ENCODING = "UTF8">>                         "%TS_CONFIG%"
   @echo ENDEXT              = ".len">>                         "%TS_CONFIG%"
   @echo PLAFEXT             = ".win">>                         "%TS_CONFIG%"
   @echo TBL                 = "tbl">>                          "%TS_CONFIG%"
   @echo ENC                 = "len">>                          "%TS_CONFIG%"

   @exit /b 0
   
::end make_config.cmd



* Exitsing Teradata - find out how these are used.

DATABASE1  = "$(DATABASEFOURG)"
PROJDIR1   = "$(DATABASE1)"
MDM_INPUT = "$(DRMDM_INPUT)"
TSS_OUTPUT = "$(DRTSS_OUTPUT)"
OUTPUT1    = "$(PROJDIR1)\data"
